/* Populate Tables */
INSERT INTO registro(ID,CIUDAD, CODIGO_POSTAL ,DEPARTAMENTO, NOMBRE_CALLE, NUMERO_CALLE, PERFIL, TIPO_DIRECCION )VALUES(1,'Bogotá',11115,'Cundinamarca','Transversal',85,1,1);
INSERT INTO registro(ID,CIUDAD, CODIGO_POSTAL ,DEPARTAMENTO, NOMBRE_CALLE, NUMERO_CALLE, PERFIL, TIPO_DIRECCION )VALUES(2,'Neiva',11115,'Huila','Avenida Siempre Viva',85,1,1);






